apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oiai-api
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: apps
    server: https://kubernetes.default.svc
  project: oiai-dev-project
  source:
    repoURL: http://dg-oiai-charts.s3-website-us-east-1.amazonaws.com/charts/
    chart: oiai-api-base-chart
    targetRevision: 1.0.0
    helm:
      values: |
        image: 132900311735.dkr.ecr.us-east-1.amazonaws.com/oiai-dev-us-east-1-api-repo:development
        imagePullSecrets: []
        api:
          initContainers:
            1-wait-for-migrations:
              image: 132900311735.dkr.ecr.us-east-1.amazonaws.com/oiai-dev-us-east-1-api-repo:development
              envFrom:
              - configMapRef:
                  name: oiai-api-configmap
              - secretRef:
                  name: {{ .Values.api.databaseSecret }}
                  command: ["alembic", "upgrade", "head"]
          command: ["uvicorn", "--host", "0.0.0.0", "--port", "8000", "app.main:app", "--reload"]
          envFrom:
          - configMapRef:
              name: oiai-api-configmap
          - secretRef:
              name: {{ .Values.api.databaseSecret }}
          autoscaling:
            enabled: true
            target: oiai-api
            minReplicas: 2
            maxReplicas: 5
            targetCPUUtilizationPercentage: 80
            targetMemoryUtilizationPercentage:  80
          resources:
            requests:
              cpu: 0.2
              memory: 0.3Gi
            limits:
              memory: 0.5Gi
          service:
            main: 
              ports:
                http:
                  port: 80
                  targetPort: 8000
          ingress:
            main:
              annotations:
                alb.ingress.kubernetes.io/group.name: oiai-dev-alb
                alb.ingress.kubernetes.io/listen-ports: "[{\"HTTPS\":443}]"
                alb.ingress.kubernetes.io/scheme: internet-facing
                alb.ingress.kubernetes.io/target-type: ip
                alb.ingress.kubernetes.io/ssl-policy: "ELBSecurityPolicy-TLS-1-2-2017-01"
                alb.ingress.kubernetes.io/success-codes: 200,301
                alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=120
                alb.ingress.kubernetes.io/certificate-arn: {{ .Values.api.alb.certificateArn }}
              enabled: true
              hosts:
              - host: api.oiai.thisguydeploys.com
                paths:
                - path: /
                  pathType: Prefix
                  service:
                    name: oiai-api
                    port: 80
              ingressClassName: alb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true